sonar.projectKey=playmaker-hub-front
sonar.projectName=playmaker-hub-front
sonar.projectVersion=0.0.0

sonar.sources=src
sonar.exclusions=**/node_modules/**, **/*.spec.ts, **/dist/**, **/coverage/**

sonar.javascript.lcov.reportPaths=coverage/playmaker-hub-front/lcov.info

sonar.host.url=http://localhost:9000

sonar.login=sqp_ba4aa22310a3cdfc70c39235747a38e67c22216b
